language: python
python:
  - 3.5

# Handle git submodules manually
git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
    $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - echo ${KEYNAME}
jobs:
  include:
    - stage: test
      script: true
    - stage: deploy
      # if: tag IS present
      script: docker run -v $(pwd):/usr/src/qfield opengisch/qfield-sdk /usr/src/qfield/scripts/docker-build.sh
env:
  global:
    secure: fYC4YWxJHQJBWfBi7K/lRx1D58n22H1xs421m6QGh8DPF+R6LvkgeoFdbi/tiG+8JnjrbYdK4pnLk3MmFVD8Qr/yDaDlbVJEGBUY+yV+G6mpfditgVPQ32YV45D1QuhENrbru2wTASkSnO6I/nQ5yacwbZiKj0w37cbAPv0Pv3M=
